### PR TITLE
UI: Small style and usage fixes

### LINKED ISSUE #72: Add change border-radius on 'Box' component
Add possibility change "Box" component border-radius using props

### LINKED ISSUE #80: Counter arrows placement issue
In some usages, Counter components need to have an increased height. Right now top and bottom arrows are sticky to the borders, while expect to be vertically centered with a static margin from each other:

Actual behavior:
image

Expected behavior:
image

Or at least it would be cool to have an ability to control such behavior.

### LINKED ISSUE #81: TextField event handlers typing lack details
Currently, `onChange` handler in `TextField` component as a first argument passes `Event` object.
There's an issue with it: in case we need to use any of `HTMLInput` properties, we have to use `as` construction for it. Basic `Event` type don't have a generic to specify what element are we actually expecting to work with.

 As soon as we're always working with `input` tag in this context, I think we can use `React.ChangeEvent<HTMLInputElement>` type on returned event.

### PR DESCRIPTION
**Pull request by p1nta**
Fix #81 
Fix #80 
Fix #72

### CODE REVIEW

File: packages/components/src/components/box/index.jsx [hunk 1]
```diff
@@ -115,6 +117,10 @@ Box.propTypes = {
    * Component border width.
    */
   strokeWidth: PropTypes.number,
+  /**
+   * Component border-radius.
```
Comment (donskov) [inline packages/components/src/components/box/index.jsx:121]: `Component border-radius.` -> `Component border-radius in pixels (px).`

File: packages/components/index.d.ts [hunk 2]
```diff
@@ -398,13 +398,13 @@ interface InpuBasicProps {
...
-interface InputProps extends InpuBasicProps {
+interface InputProps extends InputBasicProps {
   onChange?: React.ChangeEventHandler<HTMLInputElement>;
 }
 
-interface TextFieldProps extends InpuBasicProps {
-  onChange?: (e: Event, valid: boolean) => void;
-  onBlur?: (e: Event) => void;
+interface TextFieldProps extends InputBasicProps {
+  onChange?: (e: React.ChangeEvent<HTMLTextAreaElement> | React.ChangeEvent<HTMLInputElement>, valid: boolean) => void;
```
Comment (donskov) [inline packages/components/index.d.ts:406]: Some [reference](https://github.com/mui-org/material-ui/blob/next/packages/material-ui/src/InputBase/InputBase.d.ts#L142) for simplifying `onChange` event type

**Review by donskov — CHANGES_REQUESTED** [review]

**Review by donskov — APPROVED** [review]

**Comment by donskov** [comment]
@MarikTar Please test new changes `lib-react-components@1.3.1`
